services:
  - type: web
    name: rvc-webui
    env: python
    repo: https://github.com/samudhan2008/RVC-WebUI
    buildCommand: pip install -r requirements.txt
    startCommand: python infer-web.py
    envVars:
      - key: PORT
        value: 8000
      - key: CUDA_VISIBLE_DEVICES
        value: 0
